CopyFiles-Task: use class ReturncodePostcondition getErrorMessage
CopyFiles.py:
-With this change we show the error in the window that corresponds to failure_instance.

- Class DownloaderPostcondition in CopyFiles show from Task getErrorMessage class ReturncodePostcondition error log (failure_instance).
* this returns Task Error log correctly.

- Return call to self.error_message is removed.

- There are no attributes with this instance therefore we have this type of crash if failure_instance is one type Error URLError or (Others):
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
<  3313.9614>     self.error_message = failure_instance.getErrorMessage()
<  3313.9618> AttributeError: 'URLError' object has no attribute 'getErrorMessage'

Task.py:
- With "None" args, no include in callback.

Note: It must be taken into account that a for opened to a job from another module in order to be able to download URL files, can cause blocking; first, it must be ensured that there is an active job (if job) and there was no error of this type that we are dealing with.