SleepTimer improvements
* SleepTimerEdit: fix boot from deepstandby with timer actived

- Fix starting with an wakeup up from SleepTimerEdit when with recording or zap timer is activated.

- Description status for this action is updated.

* SleepTimer:fixes values standby to shutdown + wakeup only from standby

- wake up boot problem with value actived type standby_to_shutdown is corrected.
- fix wake up from standby.

* [SleepTimerEdit] small updates

 ̶-̶d̶i̶s̶a̶b̶l̶e̶ ̶p̶o̶w̶e̶r̶ ̶o̶n̶/̶o̶f̶f̶ ̶w̶h̶e̶n̶ ̶n̶o̶t̶ ̶a̶c̶t̶i̶v̶e̶ ̶a̶n̶y̶ ̶d̶a̶y̶
-check infobar instance
-sleeptimer iptv service use as dvb service
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3585, in
setSleepTimer
OverflowError: Python int too large to convert to C long

* SleepTimer: 15 second increse for standby: deepstandby to standby

The deep mode wakeup timer now starts at exactly the given value.
- An increased time (15 seconds) is added to go to standby mode from deep mode, this change is due to DVB signal problems.
- 15-20 minutes after the end timer, when I press Power after this time that I mention, the scenario I find is no signal in Infobar SNR and AGC, if I check the Satfinder if it exists.
This new method of going to Standby does not reproduce this problem.

- revised redundant text SleepTimerEdit

Co-authored-by: norhap <elfogondesegovia@gmail.com>
Co-authored-by: Dimitrij <Dima-73@inbox.lv>