CutListEditor: fix funtion executeCallback
TypeError: CutListEditor.executeCallback() missing 1 required positional argument: 'answer'

this problem in bound method Session.processDelay was present in both pythons.